[package]
name = "shard"
version = "0.1.0"
edition = "2021"

[dependencies]
sharks = "0.5.0"
bip39 = "2.1.0"
clap = "4.5.21"
anyhow = "1.0.93"
getrandom = "0.2.15"

[dev-dependencies]
quickcheck = "1.0.0"
quickcheck_macros = "1.0.0"